### ISSUE TITLE
how u generate the vendor/bb-priv/keys

### ISSUE THREAD

**Issue by fun1355** [B--B/xiaomi_msm8996-common#5]
https://github.com/B--B/xiaomi_msm8996-common/blob/60358009c176f2a14fabe5471769699b8af9cdf3/msm8996.mk#L379

I know your previous key is genertate by this scripts and locate in .android-certs in croot.
```
CN=example.com
../development/tools/make_key releasekey "/CN=$CN/"
../development/tools/make_key platform "/CN=$CN/"
../development/tools/make_key shared "/CN=$CN/"
../development/tools/make_key media "/CN=$CN/"
../development/tools/make_key networkstack "/CN=$CN/"
../development/tools/make_key sdk_sandbox "/CN=$CN/"
../development/tools/make_key bluetooth "/CN=$CN/"
../development/tools/make_key testkey "/CN=$CN/"
openssl genrsa 4096 | openssl pkcs8 -topk8 -scrypt -out avb.pem
.../external/avb/avbtool extract_public_key --key avb.pem --output avb_pkmd.bin
 signify -G -n -p factory.pub -s factory.sec
```
But it will raised an error, "out/bazel/output/external/soong_injection/product_config_platforms/products/aosp_gemini-user/BUILD:9:16: no such package '.android-certs': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package." 
I don't know how to handle this error, I guess it didn't do as PRODUCT_COPY_FILES. 
thx in advance.

**Comment by B--B** [comment]
You need to add a bazel BUILD file in vendor/bb-priv/keys/ directory : https://github.com/PixelExperience-Staging/build/blob/fourteen/target/product/security/BUILD.bazel and whitelist in soong repo the keys directory path like this: https://review.lineageos.org/c/LineageOS/android_build_soong/+/369119

**Comment by fun1355** [comment]
thx, it works.
