### ISSUE TITLE
PixelExperience is dead,, do you plan to other rom like crd, evox, cherish?

### ISSUE THREAD

**Issue by fun1355** [B--B/xiaomi_msm8996-common#6]
https://github.com/PixelExperience-Staging/manifest
https://github.com/PixelExperience-Staging/vendor_aosp
and so on is deleted!

**Comment by B--B** [comment]
I've rebased all PE changes over android-14.0.0_r22 tag, tested only grus until now but apparently everything works fine you can use my repos until PE devs bring sources back
NOTE: dolby atmos support is already merged, I've also included button light support, but in a really basic way
https://github.com/Pixel-Experience-BB

**Comment by B--B** [comment]
I'm closing this as PE sources are again online, builds and boot fine, but buttons lights are half broken and stays on when screen is turned off with power button. I've already contacted one of PE devs because I'm unable to push commits on their gerrit, use the attached patch until they merge my commit or fix it in a different way

[0001-fw-b-fix-button-and-keyboard-lights-control.PATCH](https://github.com/B--B/xiaomi_msm8996-common/files/14453803/0001-fw-b-fix-button-and-keyboard-lights-control.PATCH)

**Comment by 61rd** [comment]
> I've rebased all PE changes over android-14.0.0_r22 tag, tested only grus until now but apparently everything works fine you can use my repos until PE devs bring sources back NOTE: dolby atmos support is already merged, I've also included button light support, but in a really basic way https://github.com/Pixel-Experience-BB

https://blog.pixelexperience.org/2024/04/everything-has-to-come-to-an-end-sometime/

PixelExperience is dead,, do you plan to other rom like crdroid, cherish, aospa?

**Comment by B--B** [comment]
I will release a last build this weekend for Grus and Courbet because there are some unreleased fixes, then before switching to another ROM I want to see if it's possible to update PE sources and keep them updated in a decent way at least until Android 15 comes out, but it will require some time

**Comment by 61rd** [comment]
Hi, I have tried to build TheParasiteProject with your devicetree and vendor, but it bootloop. https://github.com/TheParasiteProject/manifest. The project refers AOSP 14.0.0.r51, newer than los.  Los refers 14.0.0.r50. Do you want to based on this project.

--------------------
https://github.com/exTHmUI/android/blob/Tenshi/default.xml

refs/tags/android-13.0.0_r75

https://github.com/Project-Xtended/manifest/blob/xt/default.xml

refs/tags/android-13.0.0_r43

https://github.com/PixysOS/manifest/blob/fourteen-v2/default.xml

refs/tags/android-14.0.0_r35

https://github.com/AospExtended/manifest/blob/12.1.x/default.xml

refs/tags/android-12.1.0_r11

https://github.com/yaap/manifest/blob/fourteen/default.xml

refs/tags/android-14.0.0_r50

https://github.com/AICP/platform_manifest/blob/u14.0/default.xml

refs/tags/android-14.0.0_r35

https://github.com/ArrowOS/android_manifest/blob/arrow-13.1/default.xml

refs/tags/android-13.0.0_r75

https://github.com/StatiXOS/android_manifest/blob/udc-qpr3/default.xml

refs/tags/android-14.0.0_r50

https://github.com/PotatoProject/manifest/blob/hashbrown-release/default.xml

refs/tags/android-14.0.0_r11

https://github.com/hentaiOS/platform_manifest/blob/Ursamoon/default.xml

refs/tags/android-14.0.0_r50

https://github.com/Octavi-OS/platform_manifest/blob/12/default.xml

refs/tags/android-12.0.0_r2

https://github.com/crdroidandroid/android/blob/14.0/default.xml

refs/tags/android-14.0.0_r50

https://github.com/TheParasiteProject/manifest/blob/main/default.xml

refs/tags/android-14.0.0_r51

https://github.com/Colt-Enigma/platform_manifest/blob/c14/default.xml

refs/tags/android-14.0.0_r16

https://github.com/Havoc-OS/android_manifest/blob/thirteen/default.xml

refs/tags/android-13.0.0_r75

https://github.com/nitrogen-project/android_manifest/blob/14/default.xml

refs/tags/android-14.0.0_r50

https://github.com/PixelExtended/manifest/blob/UFO/default.xml

refs/tags/android-14.0.0_r22

https://github.com/ShapeShiftOS/android_manifest/blob/android_13/default.xml

refs/tags/android-13.0.0_r18

https://github.com/PixelExperience/manifest/blob/fourteen/default.xml

refs/tags/android-14.0.0_r22

https://github.com/syberia-project/manifest/blob/14.0/default.xml

refs/tags/android-14.0.0_r35

https://github.com/BlissRoms/platform_manifest/blob/universe/default.xml

refs/tags/android-14.0.0_r50

https://github.com/ProtonAOSP/android_manifest/blob/sc-qpr3/default.xml

refs/tags/android-12.1.0_r11

https://github.com/PixelDust-Twelve/android_manifest/blob/12/default.xml

refs/tags/android-12.1.0_r20

https://github.com/AOSPA/manifest/blob/uvite/default.xml

refs/tags/android-14.0.0_r27

https://github.com/LineageOS/android/blob/lineage-21.0/default.xml

refs/tags/android-14.0.0_r50

https://github.com/Evolution-X/manifest/blob/u/default.xml

refs/tags/android-14.0.0_r35

https://github.com/LMODroid/manifest/blob/fourteen/default.xml

refs/tags/android-14.0.0_r50

https://gitlab.com/iode/os/public/manifests/android/-/blob/v5-staging/default.xml?ref_type=heads

refs/tags/android-14.0.0_r35
